export 'logingScreen/loging_pages.dart';
export 'splashScreen/splash_page.dart';
export 'homeScreen/home_page.dart';
export 'bottomBarScreen/bottombar_page.dart';
export 'categoryScreen/category_page.dart';
export 'profileScreen/profile_page.dart';
export 'shopping_cart_screen.dart/shopping_cart_page.dart';
export 'order_screen/order_page.dart';
export 'repair_screen/repair_page.dart';